version: "3.3"

services:
  db-backup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - $LOCAL_DESTINATION:/var/destination
        - $SOURCE:/var/source
    ports:
        - 127.0.0.1:18080:18080
    env_file: .env
